### ISSUE TITLE
ID converter in README.md is invalid

### ISSUE THREAD

**Issue by parityhero** [Radioh/ha_twitch_helix#11]
The website used to convert username's to ID's is no longer available.

You can use this one I found on Google as a replacement:

https://customapi.aidenwallis.co.uk/api/v1/twitch/toID/<USERNAME>

**Comment by Radioh** [comment]
Thank you for letting me know. It's something I wanted to rework, so you don't need the channel_id and can just enter the channel username.
 
I'm going to create a new release with a breaking change in the config.
Instead of `channel_ids` and `own_channel_id` in the config there will now be a `channels `and `own_channel` which will take the username of the channel. I think this is more intuitive overall.

**Comment by Radioh** [comment]
The release https://github.com/Radioh/ha_twitch_helix/releases/tag/v.0.5.0 has been created
Let me know if you update and experience any issues with the new build.
