### ISSUE TITLE
[Question] Current Viewers

### ISSUE THREAD

**Issue by Krojack** [Radioh/ha_twitch_helix#18]
I noticed the viewers drops to 0 when the streamer goes offline. Is this due to the Twitch API returns 0 when the streamer is offline or the sensor just defaults to 0 when offline? Reason I ask is if I'm watching someone and they go offline, I noticed the viewer count on the site still shows people.

**Comment by Radioh** [comment]
Hi, 

It's most likely due to the way the stream data is retrieved and handled. If the stream data cannot be retrieved because the the stream is offline, then the python script will fall back and set the state to STATE_OFFLINE. The other values should default to None, which I think might be translated to 0.
